tagFormat: "v${version}-rc"
branches:
  #change the branch to pre-prod
  - "main"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
    - successCommentCondition: false
      failCommentCondition: false
      labels: false
      releasedLabels: false
