---
name: CI and Deploy Pipeline

on:
  push:
    branches-ignore:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  conventional-commits:
    name: Run Conventional Commits Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for ranges)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install .
          pip install -r requirements-dev.txt

      - name: Compute commit range
        id: range
        shell: bash
        run: |
          set -euo pipefail

          if [[ "${{ github.event_name }}" != "push" ]]; then
            echo "Not a push event; skipping."
            exit 0
          fi

          head_sha="${{ github.sha }}"
          base_sha="${{ github.event.before }}"

          if [[ "$base_sha" =~ ^0+$ ]]; then
          base_sha="$(git rev-list --max-parents=0 "$head_sha" | tail -n1)"
          else
            # Ensure the 'before' commit exists locally
            if ! git cat-file -e "$base_sha^{commit}" 2>/dev/null; then
            # Fetch just that commit (and its objects) efficiently
            git fetch --no-tags --prune --depth=100 \
            origin "$base_sha" || git fetch --no-tags --prune origin --depth=0
            fi
          fi

          echo "range=$base_sha..$head_sha" >> "$GITHUB_OUTPUT"
          echo "Using range: $base_sha..$head_sha"

      - name: Run Commitizen check
        if: ${{ steps.range.outputs.range != '' }}
        run: |
          range="${{ steps.range.outputs.range }}"
          if [ "$(git rev-list --count "$range")" -eq 0 ]; then
            echo "Range empty; checking last commit only"
            cz check --message "$(git log -1 --pretty=%B "${{ github.sha }}")"
          else
            cz check --rev-range "$range"
          fi

  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    needs: conventional-commits
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          black --check --diff src/ tests/
          isort --profile black --check-only src/ tests/
          pylint --disable=R0801 $(git ls-files '*.py')
          yamllint .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install .
          pip install -r requirements-dev.txt

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage html

      - name: Publish coverage to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: htmlcov

      - name: Generate coverage report in console
        run: coverage report

  audit:
    name: Run Security Audit
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run pip-audit
        run: pip-audit

  pages:
    name: Deploy coverage to GitHub Pages
    if: >-
      ${{ github.event_name != 'pull_request'
          && contains(fromJSON('["main","dev"]'), github.ref_name) }}
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4


  deploy:
    name: Sample Deploy Step
    runs-on: ubuntu-latest
    needs: [test, audit]
    if: github.ref_name != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deployment to DEV
        run: echo "Deploying from '${{ github.ref_name }}' branch"
