---
name: CI and Deploy Pipeline

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          black --check --diff src/ tests/
          isort --profile black --check-only src/ tests/
          pylint --disable=R0801 $(git ls-files '*.py')
          yamllint .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install .
          pip install -r requirements-dev.txt

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage html

      - name: Deploy coverage report to GitHub Pages
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git worktree add gh-pages origin/gh-pages || \
          git checkout --orphan gh-pages
          cp -r htmlcov/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update coverage report"
          git push -f origin HEAD:gh-pages

      - name: Generate coverage report in console
        run: coverage report

  audit:
    name: Run Security Audit
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run pip-audit
        run: pip-audit

  deploy:
    name: Sample Deploy Step
    runs-on: ubuntu-latest
    needs: [test, audit]
    if: github.ref_name != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment to DEV
        run: echo "Deploying from '${{ github.ref_name }}' branch"
