---
name: CI and Deploy Pipeline

on:
  push:
    branches-ignore:
      - gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  conventional-commits:
    name: Run Conventional Commits Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for ranges)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install .
          pip install -r requirements-dev.txt

      - name: Compute feature commit range
        id: range
        shell: bash
        run: |
          set -euo pipefail

          head_sha="${{ github.sha }}"
          base_branch="main"   #change if default branch is different

          git fetch origin "$base_branch"
          fork_point="$(git merge-base --fork-point\
          "origin/${base_branch}" "$head_sha" \
          || git merge-base "origin/${base_branch}" "$head_sha")"

          range="${fork_point}..${head_sha}"
          echo "range=$range" >> "$GITHUB_OUTPUT"
          echo "Using feature range: $range"

      - name: Run Commitizen check
        if: ${{ steps.range.outputs.range != '' }}
        run: |
          range="${{ steps.range.outputs.range }}"
          if [ "$(git rev-list --count "$range")" -eq 0 ]; then
            echo "No commits since fork point; checking last commit only"
            cz check --message "$(git log -1 --pretty=%B "${{ github.sha }}")"
          else
            echo "Checking commits in range: $range"
            cz check --rev-range "$range"
          fi

  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    needs: conventional-commits
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          black --check --diff src/ tests/
          isort --profile black --check-only src/ tests/
          pylint --disable=R0801 $(git ls-files '*.py')
          yamllint .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package and other dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install .
          pip install -r requirements-dev.txt

      - name: Run tests and generate coverage
        run: |
          coverage run -m pytest
          coverage html

      - name: Publish coverage to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: htmlcov

      - name: Generate coverage report in console
        run: coverage report

  audit:
    name: Run Security Audit
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run pip-audit
        run: pip-audit

  pages:
    name: Deploy coverage to GitHub Pages
    if: >-
      ${{ github.event_name != 'pull_request'
          && contains(fromJSON('["main","dev"]'), github.ref_name) }}
    needs: [test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4


  deploy:
    name: Sample Deploy Step
    runs-on: ubuntu-latest
    needs: [test, audit]
    if: github.ref_name != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deployment to DEV
        run: echo "Deploying from '${{ github.ref_name }}' branch"
